// Référence de l'API - miroir des routes déclarées dans saas_api/main.go et de
// leurs handlers (handlers/*.go, dto.go). À tenir à jour si une route change,
// pas d'endpoint côté API qui expose cette table (voir aussi GET /me/ai-manifest,
// qui sert un équivalent Markdown pensé pour être collé dans un assistant IA).

export const COMPONENT_TYPES_DOC = [
  "nginx", "react", "vue", "angular", "svelte",
  "nextjs", "nuxt", "sveltekit", "nodejs", "express", "nestjs",
  "python", "django", "fastapi",
  "springboot", "aspnet", "go",
  "laravel", "symfony",
  "postgres",
  "custom",
];

export const API_CATEGORIES = [
  "Authentification",
  "Compte",
  "Environnements",
  "Secrets",
  "Données",
  "Pods",
  "Observabilité",
  "Admin",
  "Système",
];

export const API_REFERENCE = [
  {
    method: "GET",
    path: "/health",
    auth: "public",
    category: "Système",
    description: "Vérifie que le service API est disponible.",
    response: { status: "ok" },
  },
  {
    method: "POST",
    path: "/clients",
    auth: "public",
    category: "Authentification",
    description: "Démarre une inscription : envoie un code à 6 chiffres par email (Brevo). Ne crée pas encore de compte - voir POST /clients/verify.",
    body: { email: "alice@example.com", password: "motdepasse123" },
    bodyNotes: [
      "email : requis, format email valide",
      "password : requis, 8 caractères minimum",
      "Toujours tier \"free\" à l'inscription - seul un admin peut faire évoluer l'abonnement ensuite (PATCH /admin/clients/:id/tier).",
    ],
    response: { email: "alice@example.com", expiresInSeconds: 900 },
    responseNotes: ["Le code expire après ce délai (15 min), 5 essais max avant de devoir relancer l'inscription."],
  },
  {
    method: "POST",
    path: "/clients/verify",
    auth: "public",
    category: "Authentification",
    description: "Finalise une inscription démarrée par POST /clients : crée le compte si le code est valide, renvoie sa clé API et un token de session.",
    body: { email: "alice@example.com", password: "motdepasse123", code: "123456" },
    bodyNotes: [
      "password : resoumis ici (jamais stocké pendant l'attente de vérification)",
      "code : requis, les 6 chiffres reçus par email",
    ],
    response: {
      clientId: "3f2a1e2b-...-uuid",
      email: "alice@example.com",
      tier: "free",
      apiKey: "sk_AbCdEf123...",
      token: "eyJ...payload.signature",
    },
    responseNotes: ["apiKey n'est affichée qu'une seule fois, à cet instant."],
  },
  {
    method: "POST",
    path: "/clients/resend-code",
    auth: "public",
    category: "Authentification",
    description: "Renvoie un nouveau code de vérification pour une inscription déjà en attente (code perdu ou expiré) - invalide l'ancien.",
    body: { email: "alice@example.com" },
    response: { email: "alice@example.com", expiresInSeconds: 900 },
  },
  {
    method: "POST",
    path: "/auth/login",
    auth: "public",
    category: "Authentification",
    description: "Authentifie un client par email/mot de passe et renvoie un token de session (7 jours).",
    body: { email: "alice@example.com", password: "motdepasse123" },
    response: {
      token: "eyJ...payload.signature",
      clientId: "3f2a1e2b-...-uuid",
      email: "alice@example.com",
      slug: "alice",
      tier: "free",
      isAdmin: false,
    },
  },
  {
    method: "GET",
    path: "/me",
    examplePath: "/me",
    auth: "authenticated",
    category: "Compte",
    description: "Renvoie les informations du compte authentifié.",
    response: {
      clientId: "3f2a1e2b-...-uuid",
      email: "alice@example.com",
      slug: "alice",
      tier: "free",
      isAdmin: false,
      keyPrefix: "sk_AbCdEf12",
    },
  },
  {
    method: "POST",
    path: "/me/password",
    examplePath: "/me/password",
    auth: "authenticated",
    category: "Compte",
    description: "Définit ou change le mot de passe du compte authentifié.",
    body: { password: "nouveauMotDePasse123" },
    bodyNotes: ["password : requis, 8 caractères minimum"],
    response: null,
    responseNotes: ["204 No Content"],
  },
  {
    method: "POST",
    path: "/me/api-key/regenerate",
    examplePath: "/me/api-key/regenerate",
    auth: "authenticated",
    category: "Compte",
    description: "Révoque la clé API active et en génère une nouvelle, affichée une seule fois.",
    response: { apiKey: "sk_NouvelleCle987..." },
    responseNotes: [
      "Si cet appel est authentifié via X-API-Key, cette clé devient invalide immédiatement après : préférer Authorization: Bearer pour ne pas se déconnecter soi-même.",
    ],
  },
  {
    method: "GET",
    path: "/me/ai-manifest",
    examplePath: "/me/ai-manifest",
    auth: "authenticated",
    category: "Compte",
    description: "Génère une documentation Markdown complète du compte (auth, endpoints, environnements actuels), pensée pour être collée dans le contexte d'un assistant IA.",
    response: null,
    responseNotes: ["Content-Type: text/markdown - pas du JSON."],
  },
  {
    method: "POST",
    path: "/namespaces",
    examplePath: "/namespaces",
    auth: "authenticated",
    category: "Environnements",
    description: "Provisionne un nouvel environnement (namespace Kubernetes) avec ses composants. Le quota suit toujours l'abonnement du client, pas configurable ici.",
    body: {
      name: "prod",
      components: [
        { name: "api", type: "nodejs", replicas: 2, env: { NODE_ENV: "production" }, expose: true },
        { name: "db", type: "postgres", expose: false },
      ],
    },
    bodyNotes: [
      "name : requis, minuscules alphanumériques + tirets - devient le suffixe de ns-<slug-client>-<name> (63 caractères max au total)",
      "components[].name : requis, commence par une lettre, minuscules alphanumériques + tirets ; exposé, <name>-<slug-client> doit tenir en 63 caractères",
      `components[].type : requis, une des ${COMPONENT_TYPES_DOC.length} valeurs valides (voir liste ci-dessous)`,
      "components[].image : obligatoire uniquement pour type \"custom\"",
      "components[].expose : jamais autorisé pour postgres (base de données : 1 réplica, volume de données et volume de sauvegardes de 5 Gi chacun)",
    ],
    response: {
      id: "8b1c...-uuid",
      name: "ns-alice-prod",
      tier: "free",
      status: "Provisioning",
      cpu: "2",
      memory: "4Gi",
      podsReady: 0,
      podsTotal: 0,
      createdAt: "2026-09-24T10:00:00Z",
      components: [
        { name: "api", type: "nodejs", image: "node:20-alpine", port: 3000, replicas: 2, status: "Provisioning", serviceHost: "api.ns-alice-prod.svc.cluster.local", url: "https://api-alice.platform.example.com" },
      ],
      grafanaDashboardUrl: "https://grafana.platform.example.com/d/...",
    },
    responseNotes: [
      "components[].generatedPassword n'apparaît qu'une fois, si un mot de passe a été auto-généré à la création - il reste ensuite consultable dans le secret <composant>-password (voir Secrets).",
      "Le provisionnement réel est asynchrone : status passe de Provisioning à Active une fois ArgoCD synchronisé.",
      "Si l'envoi vers le dépôt GitOps échoue (502), rien n'est créé : la requête peut simplement être relancée.",
    ],
  },
  {
    method: "GET",
    path: "/namespaces",
    examplePath: "/namespaces",
    auth: "authenticated",
    category: "Environnements",
    description: "Liste tous les environnements du compte authentifié, avec leur état live.",
    response: [{ name: "ns-alice-prod", status: "Active", podsReady: 2, podsTotal: 2 }],
    responseNotes: ["Tableau de NamespaceResponse (même forme que POST /namespaces)."],
  },
  {
    method: "GET",
    path: "/namespaces/:id",
    examplePath: "/namespaces/ns-exemple",
    auth: "authenticated",
    category: "Environnements",
    description: "Détail complet d'un environnement (quotas en lecture seule, pods live, composants).",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement, ex. ns-alice-prod (jamais l'UUID interne)" }],
    response: { name: "ns-alice-prod", status: "Active", cpu: "2", memory: "4Gi", components: [] },
  },
  {
    method: "POST",
    path: "/namespaces/:id/components",
    examplePath: "/namespaces/ns-exemple/components",
    auth: "authenticated",
    category: "Environnements",
    description: "Ajoute un composant à un environnement déjà existant, sans toucher aux autres composants.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    body: { name: "worker", type: "python", expose: false },
    bodyNotes: ["Même forme qu'un élément de components[] à la création (voir POST /namespaces)."],
    response: {
      name: "worker",
      type: "python",
      image: "python:3.12-slim",
      port: 8000,
      replicas: 1,
      status: "Provisioning",
      serviceHost: "worker.ns-alice-prod.svc.cluster.local",
    },
  },
  {
    method: "DELETE",
    path: "/namespaces/:id",
    examplePath: "/namespaces/ns-exemple",
    auth: "authenticated",
    category: "Environnements",
    description: "Supprime définitivement un environnement et tous ses composants.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: null,
    responseNotes: ["204 No Content."],
  },
  {
    method: "POST",
    path: "/namespaces/:id/refresh",
    examplePath: "/namespaces/ns-exemple/refresh",
    auth: "authenticated",
    category: "Environnements",
    description: "Demande à ArgoCD de resynchroniser immédiatement cet environnement, au lieu d'attendre le prochain cycle de reconciliation périodique. Déjà déclenché automatiquement après chaque création/modification (composant, déploiement, changement de tier) - utile surtout après un déploiement via la pipeline CI/CD d'un composant.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: null,
    responseNotes: [
      "204 No Content si accepté.",
      "429 si un refresh de cet environnement a déjà été demandé il y a moins de 10 secondes.",
    ],
  },
  {
    method: "PATCH",
    path: "/namespaces/:id/components/:component",
    examplePath: "/namespaces/ns-exemple/components/api",
    auth: "authenticated",
    category: "Environnements",
    description: "Reconfigure un composant existant - seule façon de le faire, aucun manifest Kubernetes brut n'est accessible. Un champ omis garde sa valeur actuelle ; un corps vide ({}) redémarre le composant sur les dernières versions de ses secrets.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "nom du composant" },
    ],
    body: { replicas: 2, env: { NODE_ENV: "production" }, secretEnv: { STRIPE_KEY: "stripe-key" } },
    bodyNotes: [
      "image, port, replicas, env, secretEnv, expose : tous optionnels",
      "env : remplace toutes les variables en clair quand fourni ({} les efface toutes)",
      "secretEnv : nom de variable -> nom d'un secret de l'environnement, même sémantique de remplacement ; le mot de passe d'une base de données reste toujours injecté",
    ],
    response: { name: "api", status: "Provisioning", env: { NODE_ENV: "production" }, secretEnv: { STRIPE_KEY: "stripe-key" } },
  },
  {
    method: "GET",
    path: "/namespaces/:id/secrets",
    examplePath: "/namespaces/ns-exemple/secrets",
    auth: "authenticated",
    category: "Secrets",
    description: "Liste les secrets de l'environnement et les composants qui les injectent - jamais de valeur.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: {
      secrets: [
        {
          name: "stripe-key",
          version: 3,
          managedBy: "client",
          usedBy: [{ component: "api", envName: "STRIPE_KEY", version: 2, pendingRestart: true }],
        },
        { name: "db-password", version: 1, managedBy: "system", usedBy: [{ component: "db", envName: "POSTGRES_PASSWORD", version: 1, pendingRestart: false }] },
      ],
      limit: 20,
      canManage: true,
    },
    responseNotes: [
      "pendingRestart : une version plus récente attend le prochain redémarrage du composant.",
      "managedBy \"system\" : mot de passe d'une base de données, créé avec elle - révélable, jamais modifiable ni supprimable.",
      "canManage est faux pour un admin sur l'environnement d'un client : noms seulement.",
    ],
  },
  {
    method: "POST",
    path: "/namespaces/:id/secrets",
    examplePath: "/namespaces/ns-exemple/secrets",
    auth: "authenticated",
    category: "Secrets",
    description: "Crée un secret dans l'environnement. Chiffré en base, jamais écrit dans le dépôt GitOps - à injecter ensuite dans un composant (secretEnv).",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    body: { name: "stripe-key", value: "sk_live_..." },
    bodyNotes: [
      "name : commence par une lettre, lettres/chiffres/_/- (100 caractères max), unique dans l'environnement",
      "value : 8 Kio max",
      "20 secrets par environnement en free, 100 en pro (403 au-delà)",
    ],
    response: { name: "stripe-key", version: 1, managedBy: "client", usedBy: [] },
  },
  {
    method: "PATCH",
    path: "/namespaces/:id/secrets/:secret",
    examplePath: "/namespaces/ns-exemple/secrets/stripe-key",
    auth: "authenticated",
    category: "Secrets",
    description: "Écrit une nouvelle valeur (nouvelle version).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":secret", description: "nom du secret" },
    ],
    body: { value: "sk_live_nouvelle", restart: true },
    bodyNotes: [
      "restart : redémarre tout de suite les composants qui injectent ce secret ; sans lui, ils gardent leur version actuelle jusqu'à leur prochain redémarrage",
    ],
    response: { name: "stripe-key", version: 4, managedBy: "client", usedBy: [] },
  },
  {
    method: "POST",
    path: "/namespaces/:id/secrets/:secret/reveal",
    examplePath: "/namespaces/ns-exemple/secrets/stripe-key/reveal",
    auth: "authenticated",
    category: "Secrets",
    description: "Révèle la valeur courante d'un secret, ou celle d'une version (?version=N). Réservé au propriétaire de l'environnement.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":secret", description: "nom du secret" },
    ],
    response: { name: "stripe-key", version: 4, value: "sk_live_nouvelle" },
  },
  {
    method: "GET",
    path: "/namespaces/:id/secrets/:secret/versions",
    examplePath: "/namespaces/ns-exemple/secrets/stripe-key/versions",
    auth: "authenticated",
    category: "Secrets",
    description: "Versions conservées d'un secret (10 dernières, plus toute version encore injectée).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":secret", description: "nom du secret" },
    ],
    response: [{ version: 4, createdAt: "2026-09-29T10:00:00Z", current: true, inUse: false }],
  },
  {
    method: "POST",
    path: "/namespaces/:id/secrets/:secret/rollback",
    examplePath: "/namespaces/ns-exemple/secrets/stripe-key/rollback",
    auth: "authenticated",
    category: "Secrets",
    description: "Restaure une version précédente, écrite comme nouvelle version (l'historique reste linéaire).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":secret", description: "nom du secret" },
    ],
    body: { version: 2, restart: true },
    response: { name: "stripe-key", version: 5, managedBy: "client", usedBy: [] },
  },
  {
    method: "DELETE",
    path: "/namespaces/:id/secrets/:secret",
    examplePath: "/namespaces/ns-exemple/secrets/stripe-key",
    auth: "authenticated",
    category: "Secrets",
    description: "Supprime un secret et son historique.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":secret", description: "nom du secret" },
    ],
    response: null,
    responseNotes: [
      "204 No Content.",
      "409 tant que le secret est injecté dans un composant - la réponse liste les composants concernés (usedBy).",
    ],
  },
  {
    method: "POST",
    path: "/namespaces/:id/databases/:component/sessions",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions",
    auth: "authenticated",
    category: "Données",
    description:
      "Ouvre une session du gestionnaire de données sur un composant postgres : l'API s'y connecte en superutilisateur et garde les connexions (fermées après 15 min d'inactivité, 5 sessions max par compte). Réservé au propriétaire de l'environnement.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
    ],
    body: { database: "", user: "", password: "" },
    bodyNotes: [
      "Tout est facultatif. Sans password, l'API utilise le mot de passe de la base (secret <composant>-password).",
      "database : par défaut celle créée avec le composant (POSTGRES_DB).",
    ],
    response: { sessionId: "9f2c...", database: "db", user: "postgres", credentialSource: "secret", databases: ["db", "postgres"], serverVersion: "16.4" },
    responseNotes: [
      "422 db_auth_failed si le mot de passe est refusé (changé depuis en SQL) : rappeler avec user et password.",
      "422 db_credentials_required si aucun mot de passe n'est connu, 503 db_unreachable si le pod ne répond pas.",
    ],
  },
  {
    method: "GET",
    path: "/namespaces/:id/databases/:component/sessions/:session/tables",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/tables",
    auth: "authenticated",
    category: "Données",
    description: "Schémas et relations (tables, vues...) de la database de la session.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    response: { schemas: ["public"], tables: [{ schema: "public", name: "clients", kind: "table", estimatedRows: 137 }] },
  },
  {
    method: "GET",
    path: "/namespaces/:id/databases/:component/sessions/:session/table",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/table?schema=public&table=clients",
    auth: "authenticated",
    category: "Données",
    description: "Structure d'une relation : colonnes, clé primaire, contraintes, index.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    queryParams: [
      { name: "schema", required: true, description: "schéma de la relation", default: "public" },
      { name: "table", required: true, description: "nom de la table ou de la vue" },
    ],
    response: {
      schema: "public",
      name: "clients",
      kind: "table",
      editable: true,
      columns: [{ name: "id", type: "bigint", nullable: false, default: "nextval('clients_id_seq'::regclass)", identity: false, generated: false }],
      primaryKey: ["id"],
      constraints: [{ name: "clients_pkey", type: "primary key", definition: "PRIMARY KEY (id)" }],
      indexes: [{ name: "clients_pkey", definition: "CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree (id)" }],
    },
  },
  {
    method: "POST",
    path: "/namespaces/:id/databases/:component/sessions/:session/tables",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/tables",
    auth: "authenticated",
    category: "Données",
    description: "Crée une table. type et default sont du SQL brut (ex. \"numeric(10,2)\", \"now()\").",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    body: {
      schema: "public",
      name: "clients",
      columns: [
        { name: "id", type: "bigserial", nullable: false, default: "", primaryKey: true },
        { name: "email", type: "text", nullable: false, default: "", primaryKey: false },
      ],
    },
    response: { schema: "public", name: "clients", kind: "table", editable: true, columns: [], primaryKey: ["id"], constraints: [], indexes: [] },
  },
  {
    method: "DELETE",
    path: "/namespaces/:id/databases/:component/sessions/:session/table",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/table?schema=public&table=clients",
    auth: "authenticated",
    category: "Données",
    description: "Supprime une table (ou une vue).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    queryParams: [
      { name: "schema", required: true, description: "schéma de la relation", default: "public" },
      { name: "table", required: true, description: "nom de la table ou de la vue" },
      { name: "cascade", required: false, description: "true : supprime aussi ce qui en dépend (vues, clés étrangères)", default: "false" },
    ],
    response: null,
    responseNotes: ["204 No Content.", "400 sql_error (SQLSTATE 2BP01) si d'autres objets en dépendent, sans cascade."],
  },
  {
    method: "GET",
    path: "/namespaces/:id/databases/:component/sessions/:session/rows",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/rows?schema=public&table=clients&limit=50",
    auth: "authenticated",
    category: "Données",
    description: "Une page de lignes. Toutes les valeurs sont du texte (null pour NULL).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    queryParams: [
      { name: "schema", required: true, description: "schéma de la relation", default: "public" },
      { name: "table", required: true, description: "nom de la table ou de la vue" },
      { name: "limit", required: false, description: "lignes par page (500 max)", default: "50" },
      { name: "offset", required: false, description: "lignes à sauter", default: "0" },
      { name: "sort", required: false, description: "colonne de tri" },
      { name: "desc", required: false, description: "true : tri décroissant", default: "false" },
      { name: "filters", required: false, description: "JSON [{column, op, value}], op : eq, neq, lt, lte, gt, gte, contains, null, notnull" },
    ],
    response: { columns: ["id", "email"], rows: [["1", "alice@exemple.com"]], keyColumns: ["id"], editable: true, hasMore: false },
    responseNotes: ["Sans clé primaire, rowIds (ctid, parallèle à rows) désigne les lignes pour la modification ou la suppression."],
  },
  {
    method: "POST",
    path: "/namespaces/:id/databases/:component/sessions/:session/rows",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/rows",
    auth: "authenticated",
    category: "Données",
    description: "Ajoute une ligne. Une colonne absente prend sa valeur par défaut ; null écrit NULL.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    body: { schema: "public", table: "clients", values: { email: "alice@exemple.com" } },
    response: { row: ["1", "alice@exemple.com"] },
  },
  {
    method: "PATCH",
    path: "/namespaces/:id/databases/:component/sessions/:session/rows",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/rows",
    auth: "authenticated",
    category: "Données",
    description: "Modifie les colonnes values de la ligne désignée par key (colonnes de la clé primaire, ou {\"$ctid\": ...} sans clé primaire).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    body: { schema: "public", table: "clients", key: { id: "1" }, values: { email: "alice@nouveau.com" } },
    response: { row: ["1", "alice@nouveau.com"] },
    responseNotes: ["409 row_not_found si la ligne a été supprimée (ou, désignée par ctid, modifiée) entre-temps."],
  },
  {
    method: "DELETE",
    path: "/namespaces/:id/databases/:component/sessions/:session/rows",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/rows",
    auth: "authenticated",
    category: "Données",
    description: "Supprime la ligne désignée par key.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    body: { schema: "public", table: "clients", key: { id: "1" } },
    response: null,
    responseNotes: ["204 No Content.", "409 row_not_found si la ligne n'existe plus."],
  },
  {
    method: "POST",
    path: "/namespaces/:id/databases/:component/sessions/:session/query",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>/query",
    auth: "authenticated",
    category: "Données",
    description:
      "Exécute du SQL libre (plusieurs instructions séparées par des « ; »). Un BEGIN reste ouvert d'un appel à l'autre, jusqu'au COMMIT ou ROLLBACK. 60 s max par instruction, 1000 lignes renvoyées max par résultat.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    body: { sql: "SELECT count(*) FROM clients;" },
    response: {
      results: [{ command: "SELECT 1", columns: ["count"], rows: [["137"]], rowCount: 1 }],
      inTransaction: false,
      transactionFailed: false,
      durationMs: 3,
    },
    responseNotes: [
      "Une erreur SQL arrête la suite et revient dans error (message, detail, hint, code, position) avec un statut 200.",
      "409 connection_lost si la connexion a été perdue pendant une transaction ouverte (elle est annulée).",
    ],
  },
  {
    method: "DELETE",
    path: "/namespaces/:id/databases/:component/sessions/:session",
    examplePath: "/namespaces/ns-exemple/databases/db/sessions/<sessionId>",
    auth: "authenticated",
    category: "Données",
    description: "Ferme la session (une transaction ouverte est annulée).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":session", description: "sessionId renvoyé à l'ouverture de la session" },
    ],
    response: null,
    responseNotes: ["204 No Content."],
  },
  {
    method: "GET",
    path: "/namespaces/:id/databases/:component/backups",
    examplePath: "/namespaces/ns-exemple/databases/db/backups",
    auth: "authenticated",
    category: "Données",
    description:
      "Sauvegardes d'un composant postgres, stockées sur son volume <composant>-backups (5 Gi) : liste, place occupée, opération en cours et dernière opération terminée. Une sauvegarde automatique de chaque database est prise tous les jours. Réservé au propriétaire de l'environnement.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
    ],
    response: {
      volumeReady: true,
      backups: [{ id: "20260930-102000-123.manual.ZGI.dump", database: "db", kind: "manual", createdAt: "2026-09-30T10:20:00.123Z", sizeBytes: 48213 }],
      databases: ["db", "postgres"],
      defaultDatabase: "db",
      usedBytes: 48213,
      limitBytes: 5368709120,
      running: null,
      last: { type: "backup", kind: "manual", backupId: "20260930-102000-123.manual.ZGI.dump", database: "db", status: "succeeded", startedAt: "2026-09-30T10:20:00Z", finishedAt: "2026-09-30T10:20:02Z" },
      nextAutoBackupAt: "2026-10-01T10:20:00Z",
    },
    responseNotes: [
      "kind : manual (manuelle, jamais supprimée d'office), auto (quotidienne, 7 gardées par database), prerestore (sauvegarde de sécurité avant restauration, 3 gardées).",
      "volumeReady false : la base n'a pas encore son volume de sauvegardes, il arrive à la prochaine régénération du composant (PATCH, même vide).",
      "503 db_unreachable si le pod de la base n'est pas prêt.",
    ],
  },
  {
    method: "POST",
    path: "/namespaces/:id/databases/:component/backups",
    examplePath: "/namespaces/ns-exemple/databases/db/backups",
    auth: "authenticated",
    category: "Données",
    description: "Lance une sauvegarde manuelle (pg_dump, format custom) d'une database. Elle tourne en tâche de fond : suivre son état avec GET .../backups.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
    ],
    body: { database: "db" },
    bodyNotes: ["database : facultatif, par défaut celle créée avec le composant (POSTGRES_DB)."],
    response: { operation: { type: "backup", kind: "manual", database: "db", status: "running", startedAt: "2026-09-30T10:20:00Z" } },
    responseNotes: [
      "202 Accepted.",
      "409 backup_busy si une sauvegarde ou une restauration est déjà en cours sur cette base, 409 backup_volume_full si les sauvegardes occupent déjà 5 Gi, 409 backup_volume_missing si le volume n'est pas encore monté.",
    ],
  },
  {
    method: "POST",
    path: "/namespaces/:id/databases/:component/backups/:backup/restore",
    examplePath: "/namespaces/ns-exemple/databases/db/backups/20260930-102000-123.manual.ZGI.dump/restore",
    auth: "authenticated",
    category: "Données",
    description:
      "Restaure une sauvegarde dans sa database d'origine, en une seule transaction : en cas d'erreur, rien n'est modifié. Les objets de la sauvegarde sont supprimés puis recréés ; ceux créés depuis sont conservés. Les sessions du gestionnaire de données sur cette base sont fermées.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":backup", description: "id de la sauvegarde (nom du fichier)" },
    ],
    body: { safetyBackup: true },
    bodyNotes: ["safetyBackup : true par défaut, sauvegarde d'abord l'état actuel de la database (kind prerestore)."],
    response: { operation: { type: "restore", kind: "manual", backupId: "20260930-102000-123.manual.ZGI.dump", database: "db", status: "running", startedAt: "2026-09-30T11:00:00Z" } },
    responseNotes: [
      "202 Accepted : suivre l'état avec GET .../backups.",
      "La restauration est annulée si une autre connexion garde une table verrouillée plus de 30 s.",
    ],
  },
  {
    method: "DELETE",
    path: "/namespaces/:id/databases/:component/backups/:backup",
    examplePath: "/namespaces/ns-exemple/databases/db/backups/20260930-102000-123.manual.ZGI.dump",
    auth: "authenticated",
    category: "Données",
    description: "Supprime une sauvegarde.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":component", description: "composant postgres" },
      { name: ":backup", description: "id de la sauvegarde (nom du fichier)" },
    ],
    response: null,
    responseNotes: ["204 No Content.", "409 backup_busy pendant une sauvegarde ou une restauration de cette base."],
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods",
    examplePath: "/namespaces/ns-exemple/pods",
    auth: "authenticated",
    category: "Pods",
    description: "État live de tous les pods d'un environnement (lecture directe Kubernetes).",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: [{ name: "api-7d8f9c-abcde", status: "Running", ready: "1/1", restarts: 0, node: "node-3" }],
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods/:pod",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple",
    auth: "authenticated",
    category: "Pods",
    description: "Détail live d'un pod (conteneurs, ressources déclarées, IP, labels).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    response: {
      name: "api-7d8f9c-abcde",
      phase: "Running",
      podIp: "10.42.1.23",
      containers: [{ name: "api", image: "node:20-alpine", ready: true, requestsCpu: "100m", limitsCpu: "500m" }],
    },
  },
  {
    method: "POST",
    path: "/namespaces/:id/pods/:pod/exec",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple/exec",
    auth: "authenticated",
    category: "Pods",
    description: "Exécute une commande shell ponctuelle (non interactive) dans un pod.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    body: { command: "ls -la /app" },
    bodyNotes: ["Exécutée comme /bin/sh -c \"<command>\" dans le premier conteneur - pas de session persistante (voir shell-ticket pour ça)."],
    response: { stdout: "total 12\ndrwxr-xr-x ...\n", stderr: "", exitCode: 0 },
  },
  {
    method: "POST",
    path: "/namespaces/:id/pods/:pod/shell-ticket",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple/shell-ticket",
    auth: "authenticated",
    category: "Pods",
    description: "Génère un jeton à usage unique (30s) pour ouvrir juste après une session shell WebSocket interactive.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    response: { ticket: "N3f8k2...base64url" },
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods/:pod/shell",
    auth: "public",
    category: "Pods",
    description: "Ouvre une session shell interactive (WebSocket) sur un pod, authentifiée par ticket à usage unique (pas par X-API-Key - le navigateur ne peut pas poser de header custom sur une connexion WebSocket).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    queryParams: [{ name: "ticket", required: true, description: "jeton obtenu via POST .../shell-ticket, valide 30s, à usage unique" }],
    notFriendly: true,
    responseNotes: ["Bascule en WebSocket - pas une requête HTTP classique, non exécutable depuis la console ci-contre."],
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods/:pod/logs",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple/logs",
    auth: "authenticated",
    category: "Pods",
    description: "Dernières lignes de logs bruts d'un pod encore actif (lecture directe Kubernetes).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod, doit encore exister dans le cluster" },
    ],
    queryParams: [{ name: "tail", required: false, description: "nombre de lignes depuis la fin", default: "200" }],
    response: { pod: "api-7d8f9c-abcde", namespace: "ns-alice-prod", logs: "2026-09-24T10:00:00Z [info] server started\n..." },
  },
  {
    method: "GET",
    path: "/namespaces/:id/logs",
    examplePath: "/namespaces/ns-exemple/logs",
    auth: "authenticated",
    category: "Observabilité",
    description: "Recherche dans l'historique des logs (Loki, 7 derniers jours) de tous les pods d'un environnement, y compris terminés/redémarrés.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    queryParams: [
      { name: "pod", required: false, description: "filtre sur un nom de pod précis" },
      { name: "q", required: false, description: "recherche texte libre dans le message (sous-chaîne, sensible à la casse)" },
      { name: "size", required: false, description: "nombre max d'entrées", default: "200, plafonné à 500" },
    ],
    response: [{ timestamp: "2026-09-24T10:00:00.123Z", pod: "api-7d8f9c-abcde", container: "api", message: "GET /health 200 3ms" }],
  },
  {
    method: "GET",
    path: "/namespaces/:id/metrics",
    examplePath: "/namespaces/ns-exemple/metrics",
    auth: "authenticated",
    category: "Observabilité",
    description: "Dernier point de métriques CPU/mémoire connu (Prometheus) pour chaque pod de l'environnement.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: [{ pod: "api-7d8f9c-abcde", timestamp: "2026-09-24T10:00:00Z", cpuCores: 0.15, memoryBytes: 134217728 }],
  },
  {
    method: "GET",
    path: "/namespaces/:id/components/summary",
    examplePath: "/namespaces/ns-exemple/components/summary",
    auth: "authenticated",
    category: "Observabilité",
    description: "Vue agrégée par composant (logs de la dernière heure + ressources courantes) pensée pour un tableau de bord.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: [{ component: "api", logCount: 4521, errorCount: 3, lastLogAt: "2026-09-24T10:00:00Z", cpuCores: 0.15, memoryBytes: 134217728 }],
  },
  {
    method: "GET",
    path: "/admin/namespaces",
    examplePath: "/admin/namespaces",
    auth: "admin",
    category: "Admin",
    description: "Liste tous les environnements de tous les clients de la plateforme.",
    response: [{ name: "ns-alice-prod", clientEmail: "alice@example.com", clientSlug: "alice", status: "Active" }],
  },
  {
    method: "PATCH",
    path: "/admin/clients/:id/tier",
    examplePath: "/admin/clients/3f2a1e2b-uuid/tier",
    auth: "admin",
    category: "Admin",
    description: "Change l'abonnement d'un client (free/pro) et réapplique immédiatement le quota du nouveau tier sur tous ses environnements déjà créés, pas seulement les futurs.",
    pathParams: [{ name: ":id", description: "clientId du client (voir GET /admin/namespaces ou la page Organisation)" }],
    body: { tier: "pro" },
    bodyNotes: ["tier : requis, \"free\" ou \"pro\" - aucune autre valeur ni quota personnalisé possible."],
    response: { clientId: "3f2a1e2b-...-uuid", email: "alice@example.com", tier: "pro", namespaceCount: 2 },
  },
];
