// Référence de l'API - miroir des routes déclarées dans saas_api/main.go et de
// leurs handlers (handlers/*.go, dto.go). À tenir à jour si une route change,
// pas d'endpoint côté API qui expose cette table (voir aussi GET /me/ai-manifest,
// qui sert un équivalent Markdown pensé pour être collé dans un assistant IA).

export const COMPONENT_TYPES_DOC = [
  "nginx", "react", "vue", "angular", "svelte",
  "nextjs", "nuxt", "sveltekit", "nodejs", "express", "nestjs",
  "python", "django", "fastapi",
  "springboot", "aspnet", "go",
  "laravel", "symfony",
  "postgres", "mysql", "mssql", "mongodb", "redis",
  "custom",
];

export const API_CATEGORIES = [
  "Authentification",
  "Compte",
  "Environnements",
  "Pods",
  "Observabilité",
  "Admin",
  "Système",
];

export const API_REFERENCE = [
  {
    method: "GET",
    path: "/health",
    auth: "public",
    category: "Système",
    description: "Vérifie que le service API est disponible.",
    response: { status: "ok" },
  },
  {
    method: "POST",
    path: "/clients",
    auth: "public",
    category: "Authentification",
    description: "Démarre une inscription : envoie un code à 6 chiffres par email (Brevo). Ne crée pas encore de compte - voir POST /clients/verify.",
    body: { email: "alice@example.com", password: "motdepasse123" },
    bodyNotes: [
      "email : requis, format email valide",
      "password : requis, 8 caractères minimum",
      "Toujours tier \"free\" à l'inscription - seul un admin peut faire évoluer l'abonnement ensuite (PATCH /admin/clients/:id/tier).",
    ],
    response: { email: "alice@example.com", expiresInSeconds: 900 },
    responseNotes: ["Le code expire après ce délai (15 min), 5 essais max avant de devoir relancer l'inscription."],
  },
  {
    method: "POST",
    path: "/clients/verify",
    auth: "public",
    category: "Authentification",
    description: "Finalise une inscription démarrée par POST /clients : crée le compte si le code est valide, renvoie sa clé API et un token de session.",
    body: { email: "alice@example.com", password: "motdepasse123", code: "123456" },
    bodyNotes: [
      "password : resoumis ici (jamais stocké pendant l'attente de vérification)",
      "code : requis, les 6 chiffres reçus par email",
    ],
    response: {
      clientId: "3f2a1e2b-...-uuid",
      email: "alice@example.com",
      tier: "free",
      apiKey: "sk_AbCdEf123...",
      token: "eyJ...payload.signature",
    },
    responseNotes: ["apiKey n'est affichée qu'une seule fois, à cet instant."],
  },
  {
    method: "POST",
    path: "/clients/resend-code",
    auth: "public",
    category: "Authentification",
    description: "Renvoie un nouveau code de vérification pour une inscription déjà en attente (code perdu ou expiré) - invalide l'ancien.",
    body: { email: "alice@example.com" },
    response: { email: "alice@example.com", expiresInSeconds: 900 },
  },
  {
    method: "POST",
    path: "/auth/login",
    auth: "public",
    category: "Authentification",
    description: "Authentifie un client par email/mot de passe et renvoie un token de session (7 jours).",
    body: { email: "alice@example.com", password: "motdepasse123" },
    response: {
      token: "eyJ...payload.signature",
      clientId: "3f2a1e2b-...-uuid",
      email: "alice@example.com",
      slug: "alice",
      tier: "free",
      isAdmin: false,
    },
  },
  {
    method: "GET",
    path: "/me",
    examplePath: "/me",
    auth: "authenticated",
    category: "Compte",
    description: "Renvoie les informations du compte authentifié.",
    response: {
      clientId: "3f2a1e2b-...-uuid",
      email: "alice@example.com",
      slug: "alice",
      tier: "free",
      isAdmin: false,
      keyPrefix: "sk_AbCdEf12",
    },
  },
  {
    method: "POST",
    path: "/me/password",
    examplePath: "/me/password",
    auth: "authenticated",
    category: "Compte",
    description: "Définit ou change le mot de passe du compte authentifié.",
    body: { password: "nouveauMotDePasse123" },
    bodyNotes: ["password : requis, 8 caractères minimum"],
    response: null,
    responseNotes: ["204 No Content"],
  },
  {
    method: "POST",
    path: "/me/api-key/regenerate",
    examplePath: "/me/api-key/regenerate",
    auth: "authenticated",
    category: "Compte",
    description: "Révoque la clé API active et en génère une nouvelle, affichée une seule fois.",
    response: { apiKey: "sk_NouvelleCle987..." },
    responseNotes: [
      "Si cet appel est authentifié via X-API-Key, cette clé devient invalide immédiatement après : préférer Authorization: Bearer pour ne pas se déconnecter soi-même.",
    ],
  },
  {
    method: "GET",
    path: "/me/ai-manifest",
    examplePath: "/me/ai-manifest",
    auth: "authenticated",
    category: "Compte",
    description: "Génère une documentation Markdown complète du compte (auth, endpoints, environnements actuels), pensée pour être collée dans le contexte d'un assistant IA.",
    response: null,
    responseNotes: ["Content-Type: text/markdown - pas du JSON."],
  },
  {
    method: "POST",
    path: "/namespaces",
    examplePath: "/namespaces",
    auth: "authenticated",
    category: "Environnements",
    description: "Provisionne un nouvel environnement (namespace Kubernetes) avec ses composants. Le quota suit toujours l'abonnement du client, pas configurable ici.",
    body: {
      name: "prod",
      components: [
        { name: "api", type: "nodejs", replicas: 2, env: { NODE_ENV: "production" }, expose: true },
        { name: "db", type: "postgres", expose: false },
      ],
    },
    bodyNotes: [
      "name : requis, minuscules alphanumériques + tirets - devient le suffixe de ns-<slug-client>-<name>",
      `components[].type : requis, une des ${COMPONENT_TYPES_DOC.length} valeurs valides (voir liste ci-dessous)`,
      "components[].image : obligatoire uniquement pour type \"custom\"",
      "components[].expose : jamais autorisé pour un type base de données (postgres, mysql, mssql, mongodb, redis)",
    ],
    response: {
      id: "8b1c...-uuid",
      name: "ns-alice-prod",
      tier: "free",
      status: "Provisioning",
      cpu: "2",
      memory: "4Gi",
      podsReady: 0,
      podsTotal: 0,
      createdAt: "2026-09-24T10:00:00Z",
      components: [
        { name: "api", type: "nodejs", image: "node:20-alpine", port: 3000, replicas: 2, status: "Provisioning", serviceHost: "api.ns-alice-prod.svc.cluster.local", url: "https://api-alice.platform.example.com" },
      ],
      grafanaDashboardUrl: "https://grafana.platform.example.com/d/...",
    },
    responseNotes: [
      "components[].generatedPassword n'apparaît qu'une fois, si un mot de passe a été auto-généré à la création.",
      "Le provisionnement réel est asynchrone : status passe de Provisioning à Active une fois ArgoCD synchronisé.",
    ],
  },
  {
    method: "GET",
    path: "/namespaces",
    examplePath: "/namespaces",
    auth: "authenticated",
    category: "Environnements",
    description: "Liste tous les environnements du compte authentifié, avec leur état live.",
    response: [{ name: "ns-alice-prod", status: "Active", podsReady: 2, podsTotal: 2 }],
    responseNotes: ["Tableau de NamespaceResponse (même forme que POST /namespaces)."],
  },
  {
    method: "GET",
    path: "/namespaces/:id",
    examplePath: "/namespaces/ns-exemple",
    auth: "authenticated",
    category: "Environnements",
    description: "Détail complet d'un environnement (quotas en lecture seule, pods live, composants).",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement, ex. ns-alice-prod (jamais l'UUID interne)" }],
    response: { name: "ns-alice-prod", status: "Active", cpu: "2", memory: "4Gi", components: [] },
  },
  {
    method: "POST",
    path: "/namespaces/:id/components",
    examplePath: "/namespaces/ns-exemple/components",
    auth: "authenticated",
    category: "Environnements",
    description: "Ajoute un composant à un environnement déjà existant, sans toucher aux autres composants.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    body: { name: "worker", type: "python", expose: false },
    bodyNotes: ["Même forme qu'un élément de components[] à la création (voir POST /namespaces)."],
    response: {
      name: "worker",
      type: "python",
      image: "python:3.12-slim",
      port: 8000,
      replicas: 1,
      status: "Provisioning",
      serviceHost: "worker.ns-alice-prod.svc.cluster.local",
    },
  },
  {
    method: "DELETE",
    path: "/namespaces/:id",
    examplePath: "/namespaces/ns-exemple",
    auth: "authenticated",
    category: "Environnements",
    description: "Supprime définitivement un environnement et tous ses composants.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: null,
    responseNotes: ["204 No Content."],
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods",
    examplePath: "/namespaces/ns-exemple/pods",
    auth: "authenticated",
    category: "Pods",
    description: "État live de tous les pods d'un environnement (lecture directe Kubernetes).",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: [{ name: "api-7d8f9c-abcde", status: "Running", ready: "1/1", restarts: 0, node: "node-3" }],
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods/:pod",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple",
    auth: "authenticated",
    category: "Pods",
    description: "Détail live d'un pod (conteneurs, ressources déclarées, IP, labels).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    response: {
      name: "api-7d8f9c-abcde",
      phase: "Running",
      podIp: "10.42.1.23",
      containers: [{ name: "api", image: "node:20-alpine", ready: true, requestsCpu: "100m", limitsCpu: "500m" }],
    },
  },
  {
    method: "POST",
    path: "/namespaces/:id/pods/:pod/exec",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple/exec",
    auth: "authenticated",
    category: "Pods",
    description: "Exécute une commande shell ponctuelle (non interactive) dans un pod.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    body: { command: "ls -la /app" },
    bodyNotes: ["Exécutée comme /bin/sh -c \"<command>\" dans le premier conteneur - pas de session persistante (voir shell-ticket pour ça)."],
    response: { stdout: "total 12\ndrwxr-xr-x ...\n", stderr: "", exitCode: 0 },
  },
  {
    method: "POST",
    path: "/namespaces/:id/pods/:pod/shell-ticket",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple/shell-ticket",
    auth: "authenticated",
    category: "Pods",
    description: "Génère un jeton à usage unique (30s) pour ouvrir juste après une session shell WebSocket interactive.",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    response: { ticket: "N3f8k2...base64url" },
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods/:pod/shell",
    auth: "public",
    category: "Pods",
    description: "Ouvre une session shell interactive (WebSocket) sur un pod, authentifiée par ticket à usage unique (pas par X-API-Key - le navigateur ne peut pas poser de header custom sur une connexion WebSocket).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod" },
    ],
    queryParams: [{ name: "ticket", required: true, description: "jeton obtenu via POST .../shell-ticket, valide 30s, à usage unique" }],
    notFriendly: true,
    responseNotes: ["Bascule en WebSocket - pas une requête HTTP classique, non exécutable depuis la console ci-contre."],
  },
  {
    method: "GET",
    path: "/namespaces/:id/pods/:pod/logs",
    examplePath: "/namespaces/ns-exemple/pods/pod-exemple/logs",
    auth: "authenticated",
    category: "Pods",
    description: "Dernières lignes de logs bruts d'un pod encore actif (lecture directe Kubernetes).",
    pathParams: [
      { name: ":id", description: "nom complet de l'environnement" },
      { name: ":pod", description: "nom exact du pod, doit encore exister dans le cluster" },
    ],
    queryParams: [{ name: "tail", required: false, description: "nombre de lignes depuis la fin", default: "200" }],
    response: { pod: "api-7d8f9c-abcde", namespace: "ns-alice-prod", logs: "2026-09-24T10:00:00Z [info] server started\n..." },
  },
  {
    method: "GET",
    path: "/namespaces/:id/logs",
    examplePath: "/namespaces/ns-exemple/logs",
    auth: "authenticated",
    category: "Observabilité",
    description: "Recherche dans l'historique des logs (Loki, 7 derniers jours) de tous les pods d'un environnement, y compris terminés/redémarrés.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    queryParams: [
      { name: "pod", required: false, description: "filtre sur un nom de pod précis" },
      { name: "q", required: false, description: "recherche texte libre dans le message (sous-chaîne, sensible à la casse)" },
      { name: "size", required: false, description: "nombre max d'entrées", default: "200, plafonné à 500" },
    ],
    response: [{ timestamp: "2026-09-24T10:00:00.123Z", pod: "api-7d8f9c-abcde", container: "api", message: "GET /health 200 3ms" }],
  },
  {
    method: "GET",
    path: "/namespaces/:id/metrics",
    examplePath: "/namespaces/ns-exemple/metrics",
    auth: "authenticated",
    category: "Observabilité",
    description: "Dernier point de métriques CPU/mémoire connu (Prometheus) pour chaque pod de l'environnement.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: [{ pod: "api-7d8f9c-abcde", timestamp: "2026-09-24T10:00:00Z", cpuCores: 0.15, memoryBytes: 134217728 }],
  },
  {
    method: "GET",
    path: "/namespaces/:id/components/summary",
    examplePath: "/namespaces/ns-exemple/components/summary",
    auth: "authenticated",
    category: "Observabilité",
    description: "Vue agrégée par composant (logs de la dernière heure + ressources courantes) pensée pour un tableau de bord.",
    pathParams: [{ name: ":id", description: "nom complet de l'environnement" }],
    response: [{ component: "api", logCount: 4521, errorCount: 3, lastLogAt: "2026-09-24T10:00:00Z", cpuCores: 0.15, memoryBytes: 134217728 }],
  },
  {
    method: "GET",
    path: "/admin/namespaces",
    examplePath: "/admin/namespaces",
    auth: "admin",
    category: "Admin",
    description: "Liste tous les environnements de tous les clients de la plateforme.",
    response: [{ name: "ns-alice-prod", clientEmail: "alice@example.com", clientSlug: "alice", status: "Active" }],
  },
  {
    method: "PATCH",
    path: "/admin/clients/:id/tier",
    examplePath: "/admin/clients/3f2a1e2b-uuid/tier",
    auth: "admin",
    category: "Admin",
    description: "Change l'abonnement d'un client (free/pro) et réapplique immédiatement le quota du nouveau tier sur tous ses environnements déjà créés, pas seulement les futurs.",
    pathParams: [{ name: ":id", description: "clientId du client (voir GET /admin/namespaces ou la page Organisation)" }],
    body: { tier: "pro" },
    bodyNotes: ["tier : requis, \"free\" ou \"pro\" - aucune autre valeur ni quota personnalisé possible."],
    response: { clientId: "3f2a1e2b-...-uuid", email: "alice@example.com", tier: "pro", namespaceCount: 2 },
  },
];
